
export const AUTHENTICATE_USER = 'AUTHENTICATE_USER';
export const DEAUTHENTICATE_USER = 'DEAUTHENTICATE_USER';

export const SET_CURRENT_PROFILE = 'SET_CURRENT_PROFILE';
export const REQUEST_USER_PROFILE = 'REQUEST_USER_PROFILE';
export const RECEIVE_USER_PROFILE = 'RECEIVE_USER_PROFILE';
export const REQUEST_USER_MEDIA = 'REQUEST_USER_MEDIA';
export const RECEIVE_USER_MEDIA = 'RECEIVE_USER_MEDIA';
export const SHOW_ALL_MEDIA = 'SHOW_ALL_MEDIA';
